# Generated by Django 3.1.7 on 2023-03-27 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardunit',
            old_name='bweb',
            new_name='bLINE',
        ),
        migrations.AlterField(
            model_name='boardunit',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
