# Generated by Django 4.1.7 on 2023-03-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0002_auto_20230327_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardunit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
